('year'=> '2008',
 'FORD FOCUS',
  'type' => 'Voiture',
  'km'=> '225 000 - 250 000 kms',
  'place'=> '5',
  'energie'=> 'Diesel',
  'boite'=> 'Manuelle',
  'image'=> 'FORD FOCUS.jpg'),
 ('year'=> '2012',
 'SKODA FABIA',
  'type' => 'Voiture',
  'km'=> '125 000 - 150 000 kms',
  'place'=> '5',
  'energie'=> 'Essence',
  'boite'=> 'Manuelle',
  'image'=> 'SKODA FABIA.jpg'),
 ('year'=> '2009',
 'NISSAN NOTE',
  'type' => 'Voiture',
  'km'=> '0 000 - 25 000 kms',
  'place'=> '5',
  'energie'=> 'Diesel',
  'boite'=> 'Manuelle',
  'image'=> 'NISSAN NOTE.jpg'),
 ('year'=> '2018',
 'CITROEN JUMPY',
  'type' => 'Voiture',
  'km'=> '25 000 - 50 000 kms',
  'place'=> '9',
  'energie'=> 'Diesel',
  'boite'=> 'Manuelle',
  'image'=> 'CITROEN JUMPY.jpg'),
 ('year'=> '2017',
 'PEUGEOT 208',
  'type' => 'Voiture',
  'km'=> '25 000 - 50 000 kms',
  'place'=> '5',
  'energie'=> 'Essence',
  'boite'=> 'Manuelle',
  'image'=> 'PEUGEOT 208.jpg'),
 ('year'=> '2000',
 'RENAULT CLIO II',
  'type' => 'Voiture',
  'km'=> '200 000 - 225 000 kms',
  'place'=> '5',
  'energie'=> 'Diesel',
  'boite'=> 'Manuelle',
  'image'=> 'RENAULT CLIO II.jpg'),
 ('year'=> '2012',
 'CITROEN JUMPER',
  'type' => 'Utilitaire',
  'km'=> '150 000 - 175 000 kms',
  'place'=> '3',
  'energie'=> 'Diesel',
  'boite'=> 'Manuelle',
  'image'=> 'CITROEN JUMPER.jpg'),
 ('year'=> '2009',
 'VOLKSWAGEN POLO',
  'type' => 'Voiture',
  'km'=> '150 000 - 175 000 kms',
  'place'=> '5',
  'energie'=> 'Essence',
  'boite'=> 'Manuelle',
  'image'=> 'VOLKSWAGEN POLO.jpg'),
 ('year'=> '2012',
 'CITROEN JUMPER',
  'type' => 'Utilitaire',
  'km'=> '200 000 - 225 000 kms',
  'place'=> '3',
  'energie'=> 'Diesel',
  'boite'=> 'Manuelle',
  'image'=> 'CITROEN JUMPER.jpg'),
 ('year'=> '2014',
 'CITROEN C3 II',
  'type' => 'Voiture',
  'km'=> '100 000 - 125 000 kms',
  'place'=> '2',
  'energie'=> 'Diesel',
  'boite'=> 'Manuelle',
  'image'=> 'CITROEN C3 II.jpg'),
 ('year'=> '2015',
 'HYUNDAI I20',
  'type' => 'Voiture',
  'km'=> '50 000 - 75 000 kms',
  'place'=> '5',
  'energie'=> 'Essence',
  'boite'=> 'Manuelle',
  'image'=> 'HYUNDAI I20.jpg'),
 ('year'=> '2016',
 'RENAULT CLIO',
  'type' => 'Voiture',
  'km'=> '100 000 - 125 000 kms',
  'place'=> '2',
  'energie'=> 'Diesel',
  'boite'=> 'Manuelle',
  'image'=> 'RENAULT CLIO.jpg'),
 ('year'=> '2009',
 'FIAT SCUDO',
  'type' => 'Voiture',
  'km'=> '200 000 - 225 000 kms',
  'place'=> '9',
  'energie'=> 'Diesel',
  'boite'=> 'Manuelle',
  'image'=> 'FIAT SCUDO.jpg'),
 ('year'=> '2007',
 'VOLKSWAGEN POLO',
  'type' => 'Voiture',
  'km'=> '100 000 - 125 000 kms',
  'place'=> '5',
  'energie'=> 'Essence',
  'boite'=> 'Manuelle',
  'image'=> 'VOLKSWAGEN POLO bis.jpg'),
 ('year'=> '2013',
 'VOLKSWAGEN GOLF',
  'type' => 'Voiture',
  'km'=> '100 000 - 125 000 kms',
  'place'=> '5',
  'energie'=> 'Essence',
  'boite'=> 'Manuelle',
  'image'=> 'VOLKSWAGEN GOLF.jpg'),
 ('year'=> '2015',
 'MERCEDES SPRINTER',
  'type' => 'Utilitaire',
  'km'=> '100 000 - 125 000 kms',
  'place'=> '3',
  'energie'=> 'Diesel',
  'boite'=> 'Manuelle',
  'image'=> 'MERCEDES SPRINTER.jpg'),
 ('year'=> '2008',
 'PEUGEOT 308',
  'type' => 'Voiture',
  'km'=> '150 000 - 175 000 kms',
  'place'=> '5',
  'energie'=> 'Diesel',
  'boite'=> 'Manuelle',
  'image'=> 'PEUGEOT 308.jpg'),
 ('year'=> '2008',
 'PEUGEOT EXPERT',
  'type' => 'Voiture',
  'km'=> '150 000 - 175 000 kms',
  'place'=> '9',
  'energie'=> 'Diesel',
  'boite'=> 'Manuelle',
  'image'=> 'PEUGEOT EXPERT.jpg'),
 ('year'=> '2011',
 'RENAULT CLIO',
  'type' => 'Voiture',
  'km'=> '150 000 - 175 000 kms',
  'place'=> '5',
  'energie'=> 'Diesel',
  'boite'=> 'Manuelle',
  'image'=> 'RENAULT CLIO bis.jpg'),
 ('year'=> '2007',
 'PEUGEOT 207',
  'type' => 'Voiture',
  'km'=> '150 000 - 175 000 kms',
  'place'=> '5',
  'energie'=> 'Diesel',
  'boite'=> 'Manuelle',
  'image'=> 'PEUGEOT 207.jpg'),
 ('year'=> '2019',
 'FIAT 500',
  'type' => 'Voiture',
  'km'=> '0 000 - 25 000 kms',
  'place'=> '4',
  'energie'=> 'Essence',
  'boite'=> 'Séquentielle',
  'image'=> 'FIAT 500.jpg'),
 ('year'=> '2007',
 'RENAULT SCENIC II',
  'type' => 'Voiture',
  'km'=> '175 000 - 200 000 kms',
  'place'=> '5',
  'energie'=> 'Diesel',
  'boite'=> 'Manuelle',
  'image'=> 'RENAULT SCENIC II.jpg'),
 ('year'=> '2012',
 'RENAULT MEGANE',
  'type' => 'Voiture',
  'km'=> '150 000 - 175 000 kms',
  'place'=> '5',
  'energie'=> 'Essence',
  'boite'=> 'Manuelle',
  'image'=> 'RENAULT MEGANE.jpg'),
 ('year'=> '2005',
 'NISSAN MICRA',
  'type' => 'Voiture',
  'km'=> '200 000 - 225 000 kms',
  'place'=> '5',
  'energie'=> 'Diesel',
  'boite'=> 'Manuelle',
  'image'=> 'NISSAN MICRA.jpg'),
 ('year'=> '2011',
 'RENAULT CLIO III',
  'type' => 'Voiture',
  'km'=> '150 000 - 175 000 kms',
  'place'=> '5',
  'energie'=> 'Diesel',
  'boite'=> 'Manuelle',
  'image'=> 'RENAULT CLIO III.jpg'),
 ('year'=> '2007',
 'CITROEN C4',
  'type' => 'Voiture',
  'km'=> '225 000 - 250 000 kms',
  'place'=> '5',
  'energie'=> 'Diesel',
  'boite'=> 'Manuelle',
  'image'=> 'CITROEN C4.jpg'),
 ('year'=> '2016',
 'RENAULT CLIO',
  'type' => 'Voiture',
  'km'=> '100 000 - 125 000 kms',
  'place'=> '5',
  'energie'=> 'Diesel',
  'boite'=> 'Manuelle',
  'image'=> 'RENAULT CLIO ter.jpg'),
 ('year'=> '2013',
 'SUZUKI SX4',
  'type' => 'Voiture',
  'km'=> '150 000 - 175 000 kms',
  'place'=> '5',
  'energie'=> 'Essence',
  'boite'=> 'Manuelle',
  'image'=> 'SUZUKI SX4.jpg'),
 ('year'=> '2008',
 'AUDI A3',
  'type' => 'Voiture',
  'km'=> '25 000 - 50 000 kms',
  'place'=> '5',
  'energie'=> 'Diesel',
  'boite'=> 'Automatique',
  'image'=> 'AUDI A3.jpg'),
 ('year'=> '2014',
 'RENAULT TRAFIC',
  'type' => 'Voiture',
  'km'=> '150 000 - 175 000 kms',
  'place'=> '9',
  'energie'=> 'Diesel',
  'boite'=> 'Manuelle',
  'image'=> 'RENAULT TRAFIC.jpg'),
 ('year'=> '2011',
 'PEUGEOT 207 SW',
  'type' => 'Voiture',
  'km'=> '50 000 - 75 000 kms',
  'place'=> '5',
  'energie'=> 'Essence',
  'boite'=> 'Manuelle',
  'image'=> 'PEUGEOT 207 SW.jpg'),
 ('year'=> '2010',
 'RENAULT CLIO III',
  'type' => 'Voiture',
  'km'=> '175 000 - 200 000 kms',
  'place'=> '2',
  'energie'=> 'Diesel',
  'boite'=> 'Manuelle',
  'image'=> 'RENAULT CLIO III bis.jpg'),
 ('year'=> '2003',
 'CITROEN C5',
  'type' => 'Voiture',
  'km'=> '250 000 - 275 000 kms',
  'place'=> '5',
  'energie'=> 'Diesel',
  'boite'=> 'Manuelle',
  'image'=> 'CITROEN C5.jpg'),
 ('year'=> '2005',
 'OPEL MERIVA',
  'type' => 'Voiture',
  'km'=> '175 000 - 200 000 kms',
  'place'=> '5',
  'energie'=> 'Diesel',
  'boite'=> 'Manuelle',
  'image'=> 'OPEL MERIVA.jpg'),
 ('year'=> '2008',
 'PEUGEOT 206',
  'type' => 'Voiture',
  'km'=> '75 000 - 100 000 kms',
  'place'=> '4',
  'energie'=> 'Essence',
  'boite'=> 'Manuelle',
  'image'=> 'PEUGEOT 206.jpg'),
 ('year'=> '1992',
 'DAIHATSU TERIOS',
  'type' => 'Voiture',
  'km'=> '25 000 - 50 000 kms',
  'place'=> '5',
  'energie'=> 'Essence',
  'boite'=> 'Manuelle',
  'image'=> 'DAIHATSU TERIOS.jpg'),
 ('year'=> '2007',
 'RENAULT TWINGO',
  'type' => 'Voiture',
  'km'=> '75 000 - 100 000 kms',
  'place'=> '4',
  'energie'=> 'Essence',
  'boite'=> 'Manuelle',
  'image'=> 'RENAULT TWINGO.jpg'),
 ('year'=> '2006',
 'AUDI A3 SPORTBACK',
  'type' => 'Voiture',
  'km'=> '200 000 - 225 000 kms',
  'place'=> '5',
  'energie'=> 'Diesel',
  'boite'=> 'Manuelle',
  'image'=> 'AUDI A3 SPORTBACK.jpg'),
 ('year'=> '2011',
 'RENAULT TWINGO',
  'type' => 'Voiture',
  'km'=> '100 000 - 125 000 kms',
  'place'=> '4',
  'energie'=> 'Essence',
  'boite'=> 'Manuelle',
  'image'=> 'RENAULT TWINGO.jpg'),
 ('year'=> '1972',
 'VOLKSWAGEN COCCINELLE',
  'type' => 'Voiture',
  'km'=> '75 000 - 100 000 kms',
  'place'=> '4',
  'energie'=> 'Essence',
  'boite'=> 'Manuelle',
  'image'=> 'VOLKSWAGEN COCCINELLE.jpg'),
 ('year'=> '2001',
 'IVECO DAILY',
  'type' => 'Utilitaire',
  'km'=> '225 000 - 250 000 kms',
  'place'=> '2',
  'energie'=> 'Diesel',
  'boite'=> 'Manuelle',
  'image'=> 'IVECO DAILY.jpg'),
 ('year'=> '2011',
 'PEUGEOT 207 SW',
  'type' => 'Voiture',
  'km'=> '150 000 - 175 000 kms',
  'place'=> '5',
  'energie'=> 'Diesel',
  'boite'=> 'Manuelle',
  'image'=> 'PEUGEOT 207 SW.jpg'),
 ('year'=> '2019',
 'KIA STONIC',
  'type' => 'Voiture',
  'km'=> '25 000 - 50 000 kms',
  'place'=> '5',
  'energie'=> 'Essence',
  'boite'=> 'Manuelle',
  'image'=> 'KIA STONIC.jpg'),
 ('year'=> '2020',
 'TESLA MODEL 3',
  'type' => 'Voiture',
  'km'=> '0 000 - 25 000 kms',
  'place'=> '5',
  'energie'=> 'Electrique',
  'boite'=> 'Automatique',
  'image'=> 'TESLA MODEL 3.jpg'),
 ('year'=> '2010',
 'RENAULT TWINGO II',
  'type' => 'Voiture',
  'km'=> '150 000 - 175 000 kms',
  'place'=> '4',
  'energie'=> 'Essence',
  'boite'=> 'Manuelle',
  'image'=> 'RENAULT TWINGO II.jpg');